
export default new Map([
["src/content/curriculum/chinese/l1-pid.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcurriculum%2Fchinese%2Fl1-pid.mdx&astroContentModuleFlag=true")],
["src/content/curriculum/chinese/l2-lqr-state-feedback.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcurriculum%2Fchinese%2Fl2-lqr-state-feedback.mdx&astroContentModuleFlag=true")],
["src/content/curriculum/chinese/l3-smc.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcurriculum%2Fchinese%2Fl3-smc.mdx&astroContentModuleFlag=true")],
["src/content/curriculum/chinese/l4-gain-scheduling-lpv.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcurriculum%2Fchinese%2Fl4-gain-scheduling-lpv.mdx&astroContentModuleFlag=true")],
["src/content/curriculum/chinese/l5-lpv-smc-fdi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcurriculum%2Fchinese%2Fl5-lpv-smc-fdi.mdx&astroContentModuleFlag=true")],
["src/content/curriculum/english/l1-pid.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcurriculum%2Fenglish%2Fl1-pid.mdx&astroContentModuleFlag=true")],
["src/content/curriculum/english/l2-lqr-state-feedback.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcurriculum%2Fenglish%2Fl2-lqr-state-feedback.mdx&astroContentModuleFlag=true")],
["src/content/curriculum/english/l3-smc.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcurriculum%2Fenglish%2Fl3-smc.mdx&astroContentModuleFlag=true")],
["src/content/curriculum/english/l4-gain-scheduling-lpv.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcurriculum%2Fenglish%2Fl4-gain-scheduling-lpv.mdx&astroContentModuleFlag=true")],
["src/content/curriculum/english/l5-lpv-smc-fdi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcurriculum%2Fenglish%2Fl5-lpv-smc-fdi.mdx&astroContentModuleFlag=true")]]);
		